
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Header from '@/components/shared/Header/Header'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import Footer from '@/components/shared/Footer/Footer'
import { Toaster } from '@/components/ui/sonner'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wibutime',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
          >
            <Header />
            <main className='min-h-dvh pt-20 px-4 max-w-[1300px] mx-auto'>
              {children}
            </main>
            <Toaster />
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
