
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/shared/Header/Header'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import Footer from '@/components/shared/Footer/Footer'
import PageAnimatePresence from '@/components/shared/PageAnimatePresence/PageAnimatePresence'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wibutime',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
        >
          <Header />
          <PageAnimatePresence>
            <main className='min-h-dvh pt-20 px-4 max-w-[1300px] mx-auto'>
              {children}
            </main>
          </PageAnimatePresence>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
