import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Wibutime :: Login',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section>
      {children}
    </section>
  )
}
